<?php
/**
 * Blocks Initializer
 *
 * Modern block asset loading for build output generated by @wordpress/scripts.
 *
 * @package DJ
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Register block assets and block type.
 */
function stockinfo_block_cgb_init() {
	$build_dir = plugin_dir_path( __DIR__ ) . 'build/';
	$asset_path = $build_dir . 'index.asset.php';
	if ( ! file_exists( $asset_path ) ) {
		return;
	}

	$asset = include $asset_path;
	$script_handle = 'stock_information-dj-block-js';
	$style_handle = 'stock_information-style-css';
	$editor_style_handle = 'stock_information-dj-block-editor-css';

	wp_register_script(
		$script_handle,
		plugins_url( 'build/index.js', dirname( __FILE__ ) ),
		isset( $asset['dependencies'] ) ? $asset['dependencies'] : array(),
		isset( $asset['version'] ) ? $asset['version'] : null,
		true
	);

	$stockinfo_config = get_option( \StockInfo\StockInfo_Settings_Constants::API_OPTIONS );
	$params = array(
		'host'         => $stockinfo_config[ \StockInfo\StockInfo_Settings_Constants::META_API__ID__HOST ],
		'entrypoint'   => $stockinfo_config[ \StockInfo\StockInfo_Settings_Constants::META_API__ID__ENTRYPOINT ],
		'token'        => $stockinfo_config[ \StockInfo\StockInfo_Settings_Constants::META_API__ID__TOKEN ],
		'stroke_color' => $stockinfo_config[ \StockInfo\StockInfo_Settings_Constants::META_API__ID__COLOR ],
	);
	wp_localize_script( $script_handle, 'stockinfo_config', $params );

	wp_register_style(
		$style_handle,
		plugins_url( 'build/style-index.css', dirname( __FILE__ ) ),
		array(),
		file_exists( $build_dir . 'style-index.css' ) ? filemtime( $build_dir . 'style-index.css' ) : null
	);

	wp_register_style(
		$editor_style_handle,
		plugins_url( 'build/index.css', dirname( __FILE__ ) ),
		array( 'wp-edit-blocks' ),
		file_exists( $build_dir . 'index.css' ) ? filemtime( $build_dir . 'index.css' ) : null
	);

	register_block_type(
		'dj/stockinfo',
		array(
			'editor_script' => $script_handle,
			'script'        => $script_handle,
			'style'         => $style_handle,
			'editor_style'  => $editor_style_handle,
		)
	);
}

add_action( 'init', __NAMESPACE__ . '\stockinfo_block_cgb_init' );
